# Generated by Django 4.2.2 on 2023-06-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatomodel',
            old_name='fecha_naciemiento',
            new_name='fecha_nacimiento',
        ),
    ]
